name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 16, 18]

    name: '${{ matrix.platform }}: node.js ${{ matrix.node-version }}'

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Update npm to Latest
        run: npm install --global npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true